server:
  port: 9393
  servlet:
    context-path: /api/v1
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://docker_mysql:3306/test_database?useUnicode=true&characterEncoding=utf8&serverTimezone=CTT&useSSL=false
    username: root
    password: 20201102Mima!
jwt:
  tokenHeader: Authentication
  tokenPrefix: Bearer
  secret: breaker93_jwt
  expiration: 6000000  # 100分钟
logging:
  file:
    path: ./log/
    max-size: 5MB
  level:
    com.breaker.ssi: debug
file:
  upload-url: /work/data/upload/